name = "riddles"
main = "worker/src/index.js" # Path to your worker entry point
compatibility_date = "2024-04-01"

[assets]
directory = "./" # Folder containing your index.html and assets
binding = "ASSETS"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAAB7QSd0CO5eotyUL"